---
- name: Install KVM on Ubuntu and CentOS hosts
  hosts: all
  become: yes
  tasks:
#    - name: Install KVM and related packages on Ubuntu
#      apt:
#        name:
#          - qemu-kvm
#          - libvirt-daemon-system
#          - libvirt-clients
#          - bridge-utils
#          - virt-manager
#        state: present
#      when: ansible_os_family == "Debian"

    - name: Install KVM and related packages on CentOS
      yum:
        name:
          - qemu-kvm
          - libvirt
#          - libvirt-python
          - libguestfs-tools
          - virt-install
          - cockpit
          - cockpit-machines
        state: present
#      when: ansible_os_family == "RedHat"
    - name: Enable and start Cockpip service
      systemd:
        name: cockpit.socket
        enabled: yes
        state: started
    - name: Enable and start libvirt service
      systemd:
        name: libvirtd
        enabled: yes
        state: started

